import AxiomCandidateFounderFinalReleaseDecisionPayloadReturnHoldShellSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionPayloadReturnHoldShellSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionPayloadReturnHoldShellPage() {
  return <AxiomCandidateFounderFinalReleaseDecisionPayloadReturnHoldShellSurface />;
}
