import AxiomCandidateFounderFinalReleaseDecisionPayloadValidationReceiptShellSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionPayloadValidationReceiptShellSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionPayloadValidationReceiptShellPage() {
  return <AxiomCandidateFounderFinalReleaseDecisionPayloadValidationReceiptShellSurface />;
}
