import AxiomCandidateFounderFinalReleaseDecisionHandoffManifestSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionHandoffManifestSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionHandoffManifestPage() {
  return <AxiomCandidateFounderFinalReleaseDecisionHandoffManifestSurface />;
}
