import AxiomCandidateFounderFinalReleaseDecisionReceiptShellSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionReceiptShellSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionReceiptShellPage() {
  return <AxiomCandidateFounderFinalReleaseDecisionReceiptShellSurface />;
}
