import AxiomCandidateFounderFinalReleaseDecisionPayloadShellSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionPayloadShellSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionPayloadShellPage() {
  return <AxiomCandidateFounderFinalReleaseDecisionPayloadShellSurface />;
}
