import AxiomCandidateFounderFinalReleaseDecisionPayloadValidationGateSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionPayloadValidationGateSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionPayloadValidationGatePage() {
  return <AxiomCandidateFounderFinalReleaseDecisionPayloadValidationGateSurface />;
}
