import AxiomCandidateFounderFinalReleaseDecisionIngestionContractSurface from '@/components/axiom/AxiomCandidateFounderFinalReleaseDecisionIngestionContractSurface';

export default function AxiomNextNblCandidateFounderFinalReleaseDecisionIngestionContractPage() {
  return <AxiomCandidateFounderFinalReleaseDecisionIngestionContractSurface />;
}
